### ISSUE TITLE
ソースコードのドキュメント化

### ISSUE THREAD

**Issue by Nagkei10** [omnius-labs/core#72]
## Goal

ドキュメントが完成する

## Motivation

ドキュメントを作成しなければということで。

## Schedule (optional)

APIのドキュメントが完成すること

## Tasks (optional)

- [ ] ソースコードにドキュメントをつける
- [ ] ドキュメントをHTML化
- [ ] RocketPackのドキュメント化

**Comment by lyrise** [comment]
docfxとか使いたいです
